// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1P3C2yBWNDTzAJo2IK-wRmwoBIS7iUIw',
    appId: '1:1034479472102:web:d01857db69806f12f5da27',
    messagingSenderId: '1034479472102',
    projectId: 'boulderball-b3d59',
    authDomain: 'boulderball-b3d59.firebaseapp.com',
    storageBucket: 'boulderball-b3d59.appspot.com',
    measurementId: 'G-F8CW9TERKM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCg9zlzlI7aORfnD4tMtZFr1vANumWz_8',
    appId: '1:1034479472102:android:f3f8301a020ed4bff5da27',
    messagingSenderId: '1034479472102',
    projectId: 'boulderball-b3d59',
    storageBucket: 'boulderball-b3d59.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj9xu0kK0tJTh-15-lzgNvfsJ_DMrrJH8',
    appId: '1:1034479472102:ios:6a8486096618368ff5da27',
    messagingSenderId: '1034479472102',
    projectId: 'boulderball-b3d59',
    storageBucket: 'boulderball-b3d59.appspot.com',
    iosClientId:
        '1034479472102-gluj2jnlgi9agpjon1t6lj72titpq1n0.apps.googleusercontent.com',
    iosBundleId: 'com.boulderball.boulderball',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj9xu0kK0tJTh-15-lzgNvfsJ_DMrrJH8',
    appId: '1:1034479472102:ios:6a8486096618368ff5da27',
    messagingSenderId: '1034479472102',
    projectId: 'boulderball-b3d59',
    storageBucket: 'boulderball-b3d59.appspot.com',
    iosClientId:
        '1034479472102-gluj2jnlgi9agpjon1t6lj72titpq1n0.apps.googleusercontent.com',
    iosBundleId: 'com.boulderball.boulderball',
  );
}
